// Builds css/tokens.css from tokens/*.json with Style Dictionary.
// Run: npm run tokens
//
// Naming (kept identical to the WSA portal prototype so the two stay interchangeable):
//   Color/<Group>/<leaf>   -> --color-<leaf>          e.g. --color-primary-d1, --color-primary-d1-4 (the "4%" alpha step)
//   Spacing/<leaf>         -> --<leaf>                e.g. --spacing-3
//   Border Radius/<leaf>   -> --<leaf>                e.g. --rounded-md
//   Opacity/<leaf>         -> --<leaf>                e.g. --translucent-1 (as 0–1)
//   Shadow/<leaf>          -> --shadow-<leaf>
//   Font/<leaf>            -> --font-<leaf>
//   Size/<leaf>            -> --font-size-<leaf>      responsive: mobile 0+, tablet 576+, desktop 1200+
//   <Semantic>/<leaf>      -> --<group>-<leaf>        e.g. --action-primary-hover (aliases a --color-* var)

import StyleDictionary from 'style-dictionary';
import { usesReferences, getReferences } from 'style-dictionary/utils';

const slug = (s) => String(s).toLowerCase().replace(/%/g, '').replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
const SEMANTIC = ['Text', 'Action', 'Table', 'Card', 'Translucent', 'Utility'];

function cssName(path) {
  const [group, ...rest] = path;
  const leaf = slug(rest[rest.length - 1]);
  if (group === 'Color') return `color-${leaf}`;
  if (group === 'Spacing' || group === 'Border Radius' || group === 'Opacity') return leaf;
  if (group === 'Shadow') return `shadow-${leaf}`;
  if (group === 'Font') return `font-${leaf}`;
  if (group === 'Size') return `font-size-${leaf}`;
  if (SEMANTIC.includes(group)) return `${slug(group)}-${leaf}`;
  return path.map(slug).join('-');
}

function hexToRgb(hex) {
  const n = parseInt(hex.slice(1), 16);
  return [(n >> 16) & 255, (n >> 8) & 255, n & 255];
}

function cssValue(token) {
  const v = token.$value;
  const [group] = token.path;
  if (token.$type === 'color' && typeof v === 'object') {
    const a = Math.round(v.alpha * 100) / 100;
    return a >= 1 ? v.hex.toUpperCase() : `rgba(${hexToRgb(v.hex).join(', ')}, ${a})`;
  }
  if (token.$type === 'shadow') {
    return `${v.offsetX}px ${v.offsetY}px ${v.blur}px ${v.spread}px rgba(${hexToRgb(v.color).join(', ')}, ${v.alpha})`;
  }
  if (group === 'Opacity') return String(v / 100);
  if (group === 'Spacing' || group === 'Border Radius') return `${v}px`;
  return String(v);
}

StyleDictionary.registerFormat({
  name: 'css/wsa',
  format: ({ dictionary }) => {
    const base = [];
    const tablet = [];
    const desktop = [];
    for (const token of dictionary.allTokens) {
      const [group, sub] = token.path;
      // Card blur/spread numbers are baked into the Shadow tokens.
      if (group === 'Color' && sub === 'Utility' && token.path.includes('Card')) continue;
      const name = `--${cssName(token.path)}`;
      const original = token.original.$value;
      if (typeof original === 'string' && usesReferences(original)) {
        const [ref] = getReferences(original, dictionary.tokens, { usesDtcg: true });
        base.push(`  ${name}: var(--${cssName(ref.path)});`);
      } else if (group === 'Size') {
        const { mobile, tablet: t, desktop: d } = token.$value;
        base.push(`  ${name}: ${mobile}px;`);
        tablet.push(`    ${name}: ${t}px;`);
        desktop.push(`    ${name}: ${d}px;`);
      } else {
        base.push(`  ${name}: ${cssValue(token)};`);
      }
    }
    return [
      '/* Generated by scripts/build-tokens.mjs from tokens/*.json. Do not edit by hand. */',
      ':root {',
      ...base,
      '}',
      '@media (min-width: 576px) {',
      '  :root {',
      ...tablet,
      '  }',
      '}',
      '@media (min-width: 1200px) {',
      '  :root {',
      ...desktop,
      '  }',
      '}',
      '',
    ].join('\n');
  },
});

const sd = new StyleDictionary({
  source: ['tokens/foundations.json', 'tokens/typography.json', 'tokens/effects.json', 'tokens/semantic.json'],
  usesDtcg: true,
  log: { verbosity: 'default', warnings: 'disabled' },
  platforms: {
    css: {
      buildPath: 'css/',
      files: [{ destination: 'tokens.css', format: 'css/wsa' }],
    },
  },
});

await sd.buildAllPlatforms();
